project:
  type: website
  output-dir: docs

website:
  title: "Santiago Rodriguez"
  site-url: "https://saintrod.github.io/portfolio/"
  favicon: static/favicon.png
  description: "My portfolio"
  bread-crumbs: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Portfolio
        href: about.qmd
    right:
      - icon: file-person-fill
        href: posts/resume/resume.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/santiagorodriguez91/
      - icon: github
        href: https://github.com/SaintRod/
      - icon: gitlab
        href: https://gitlab.com/hail_hydra

  sidebar:
    id: id-portfolio
    style: "docked"
    search: true
    pinned: true
    contents:
        - section: Blogs
          href: posts/blogs/blogs.qmd
          contents:
            - posts/blogs/fda.qmd
            - posts/blogs/personal.qmd
        - section: Projects
          href: posts/projects/projects.qmd
          contents:
            - section: Analyses
              href: posts/projects/analyses/analyses.qmd
              contents: 
                - posts/projects/analyses/arxiv-stats-pkgs.qmd
                - posts/projects/analyses/internet-outage.qmd
            - section: Data
              href: posts/projects/data/data.qmd
              contents:
                - posts/projects/data/household-energy-pipeline.qmd
            # - section: Causal ML
            #   href: 
            # - section: ML
            #   href: posts/projects/ml/ml.qmd
            - section: Stats
              href: posts/projects/stats/stats.qmd
              contents:
                - posts/projects/stats/hypothesis-testing-primer.qmd
            - section: Time Series
              href: posts/projects/time-series/time-series.qmd
              contents:
                - posts/projects/time-series/household-forecasting.qmd
            - section: Tools
              href: posts/projects/tools/tools.qmd
              contents:
                - posts/projects/tools/mult-lang-proj-template.qmd
            - section: Visualizations
              href: "posts/viz/viz.qmd"
              contents:
                - posts/viz/job-search-dashboard.qmd
            - section: Web Apps
              href: posts/projects/web-apps/web-apps.qmd
              contents:
                - posts/projects/web-apps/tpwd.qmd
                - posts/projects/web-apps/strat-sampling-tool.qmd
        - section: Talks
          href: posts/talks/talks.qmd
          contents:
            - posts/talks/r-in-energy.qmd
        - section: Other
          href: posts/other/other.qmd
          contents:
            - posts/other/study-guides.qmd

  page-footer: 
    background: dark 
    left: © 2024 Santiago Rodriguez
    right: Built with Quarto

format:
  html:
    theme: flatly
    toc: true
    css: styles.css