---
title: "Web Apps"
format:
  html:
    toc: true
editor: source
---

# Texas Parks and Wildlife Drive Time and Distance Calculator

Years ago when I moved to Texas from South Florida I missed going fishing. I discovered that during winter months, Texas Parks & Wildlife (TPWD) stocks local fishing areas with trout. This was music to my ears. However, the static HTML table [provided](https://tpwd.texas.gov/fishboat/fish/management/stocking/trout_stocking.phtml) by TPWD wasn't conducive to getting outdoors. The problem with the static table is it only provides the fishing area and the city, and it's too tedious to search each location individually on Google Maps for example. So, I built a Shiny app for myself and hosted it on ShinyApps.io ([link](https://kaladin-stormblessed.shinyapps.io/Texas_Parks_Wildlife_Trout_Schedule/)). The app was successful and I was able to go fishing. The main goal of this version was to help me find the nearest fishing location and to be able to sort and filter locations.

Recently, I decided to learn more about putting a Shiny app in production. I decided to focus on the TPWD trout POC I built years ago because I thought others could benefit from having a better interface to the trout stocking data. The scope of the app expanded beyond just the trout stocking data though as I realized that other TPWD resources were useful but not interactive. The static nature of the resources might deter some people from getting outdoors. So, I built this Shiny app.

The goal of this app is to help Texans interact with Texas Parks & Wildlife static online resources and to help Texans get outdoors.

- web app [code](https://gitlab.com/texas_parks_and_wildlife/table_utilities/webapp)
- data layer [code](https://gitlab.com/texas_parks_and_wildlife/table_utilities/data)
- [website](http://tableswebapp.thealgo.group/)
- [Shiny contest 2024](https://forum.posit.co/t/texas-parks-wildlife-drive-time-distance-calculator-shiny-contest-submission/190999)

The web app is hosted on AWS using their free tier.
Once the 12-months free expires, depending on the cost to maintain the website the link above my not exist.
However, the code is readily available.

## Technical Details

Functionality:

- Interactive tables
- Calculate drive time and distance

Tables:

- Boat ramps
- Catfish stocking information
- Parks (list of state parks)
- Trout stocking information (new season begins in November)
- Wildlife management areas

Hosting:

- AWS EC2 (free tier t2.micro)

Software:
 
- Shiny (R) built with the Rhino development framework
- HERE API for route calculation logic
- Docker

# Stratified sampling tool

During my tenure at Consumers Energy, my sibling team was responsible for generating customer contact lists for Marketing teams.
Mostly these lists were created via simple random sampling.
However, there were some astute stakeholders that wanted to test if stratified sampling would yield more accurate results.
Initially, the team accomplished this manually, but it was error-prone and onerous.
So, I built a Shiny app for them to automate the task.
Below is a replica of that work.

- [webapp](https://kaladin-stormblessed.shinyapps.io/SamplingTool/)
- [code](https://gitlab.com/hail_hydra/sampling_tool)